### ISSUE TITLE
投稿されない

### ISSUE THREAD

**Issue by 98zinkun** [oonyaTeam/memory_share#248]
投稿ページにいった後、投稿するボタンを押しても投稿されない
トーストすら出ない
-

## バグを直した後の挙動
失敗したとしてもトーストが出るようになってほしい
-

## 修正すべきファイル
わからん
-

## スクリーンショット
<img width="611" alt="スクリーンショット 2021-10-04 13 34 38" src="https://user-images.githubusercontent.com/85686526/135795277-df23c321-acf4-4d79-b5c6-789e9b7f3e3e.png">

**Comment by 98zinkun** [comment]
画像は投稿するボタンを押したときのRUN画面

**Comment by 98zinkun** [comment]
実機の問題かも。
PC1でビルド、実機１おかしい。
PC2でビルド、実機２OK
PC2でビルド、実機１おかしい
以上の理由より実機１がおかしいと判断

**Comment by MAAAARCY** [comment]
https://stackoverflow.com/questions/37834292/i-system-out-httplog-static-issbsettingenabled-false

**Comment by MAAAARCY** [comment]
これ見た感じ、メインスレッドでの処理がスタックしてる可能性がある気がする。

**Comment by kobapi28** [comment]
これどんな感じだっけ？
toast失敗で、firebaseの方に上がってるなら僕と一緒になった(launchMode違うけど)

@98zinkun

**Comment by takumma** [comment]
解決したので閉じます
