### ISSUE TITLE
UIの修正

### ISSUE THREAD

**Issue by kobapi28** [oonyaTeam/memory_share#254]
## どういったバグが起きているか

- [x] signinのボタンが小さくなっている

- たぶんコンポーネントの横幅をコンポーネント内で設定した時の名残とかが残ってそう？(ほんまか？)

## バグを直した後の挙動

-

## 修正すべきファイル

-

## スクリーンショット

**Comment by takumma** [comment]
ボタンサイズを横幅からとってるからなのは多分そうで、ipadとかでやると破滅してしまいそうなので普通にサイズ指定してしまうほうがよさそう

**Comment by kobapi28** [comment]
普通にサイズ指定、他のtextboxとかもそうするってこと？
例えばxperiaとpixelで横幅違うと思うんだけど、どちらの横幅でもボタンサイズは同じっていう認識でよろしい？

**Comment by kobapi28** [comment]
- [x] disableの時のボタンスタイルが違う(add_sub_episode)

**Comment by kobapi28** [comment]
- [ ] add_sub_episodeとかのテキストエリアでmarginが取れてない(横の)

**Comment by kobapi28** [comment]
- [ ] 足跡の間隔を修正する(これはデザイナーのミス)

**Comment by kobapi28** [comment]
- [x] signup画面でスタイルがあたっていない

**Comment by kobapi28** [comment]
> ボタンサイズを横幅からとってるからなのは多分そうで、ipadとかでやると破滅してしまいそうなので普通にサイズ指定してしまうほうがよさそう

これなんですけど、シンプルに -48 ではなく -246 になっていて、小さくなっていました(なんで)

**Comment by takumma** [comment]
ダイアログの背景が、figmaより濃い（黒い）ような気がする

**Comment by kobapi28** [comment]
これいったんcloseします(UIの修正項目が多かったので1つにまとめるべきではないとの観点から)
