### ISSUE TITLE
add_sub_episodeで入力してもボタンがdisableのまま

### ISSUE THREAD

**Issue by kobapi28** [oonyaTeam/memory_share#255]
## どういったバグが起きているか

- サブエピソードの入力ページで追加してもボタンが灰色のままなので、そこを修正する
- サブエピソードを削除するボタンが値としてマージンを持っているのでそれを、画面の横幅をとって表示させる。

## バグを直した後の挙動

-

## 修正すべきファイル

-

## スクリーンショット

**Comment by kobapi28** [comment]
[sub_episode_page] (動いていない方)
https://github.com/oonyaTeam/memory_share/blob/dev/lib/pages/add_sub_episode_page/add_sub_episode_page.dart#L51-L53

[post_page] (動いている方)
https://github.com/oonyaTeam/memory_share/blob/dev/lib/pages/post_page/post_page.dart#L51-L53

```
primary: ()
```
かっこのあるなしで変わるのか、viewModelの更新ができていないのかっていう2通りの可能性？(sub_episodeが追加されてるのでviewModelの更新がうまくいってない説は薄そう)

**Comment by 98zinkun** [comment]
灰色のままになってるやつはマーシーが直した。
僕は削除ボタンの位置がおかしいのを直します。
