### ISSUE TITLE
サブエピソードやメインのエピソードのダイアログが表示される時に、通知を表示する

### ISSUE THREAD

**Issue by takumma** [oonyaTeam/memory_share#274]
## 追加する機能

- サブエピソードやメインエピソードの表示の時に、ずっとスマホを見続けるのはよくないので通知表示を実装する
- 要検討機能
- 実装するなら、通知設定ができるようにするべき

## 編集するファイル

-

**Comment by kobapi28** [comment]
バイブレーションほしいよなあ。。。
